/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package лось.лаба.pkg11.задание.pkg10;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class SelectKey extends javax.swing.JDialog {

    private String task;
    public SelectKey(java.awt.Frame parent, boolean modal, String task) {
        super(parent, modal);
        initComponents();
        this.task=task;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Value_k = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Fields = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Значение");

        Value_k.setEnabled(false);

        jButton1.setText("Найти");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Fields.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите ключ", "Номер полёта", "Дата вылета Формат: дд.мм.гггг чч:мм", "Пункт назначения", "Суммарная масса" }));
        Fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldsActionPerformed(evt);
            }
        });

        jButton2.setText("Отмена");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addComponent(Fields, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Value_k))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Value_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Value_k.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Заполните поле Значение");
            return;
        }
        String item = (String)Fields.getSelectedItem();      
        MainWindow.Key=transformChoose(item);
        MainWindow.Value=Value_k.getText();
        MainWindow.done=true;
        MainWindow.result_message=task+' '+item+" со значением "+Value_k.getText()+"\n";
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 private String transformChoose(String choosed_field)
    {
        switch(choosed_field)
        {
            case "Номер полёта":
                return "number_of_flight";
            case "Дата вылета Формат: дд.мм.гггг чч:мм":
                return "date_of_flight";
            case "Пункт назначения":
                return "destination";
            case "Суммарная масса":
                return "weight";
            default:
                return "";
        }
    }
    private void FieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldsActionPerformed
        JComboBox box = (JComboBox)evt.getSource();
        String item = (String)box.getSelectedItem();
        if (item.compareTo("Выберите ключ")==0)
        {
            jButton1.setEnabled(false);
            Value_k.setEnabled(false);
        }
        else
        {
           jButton1.setEnabled(true);
           Value_k.setEnabled(true);
        }
    }//GEN-LAST:event_FieldsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Fields;
    private javax.swing.JTextField Value_k;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
